// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8IQQQCGQID63hgMDQLm3Mw7Rap6DDc94',
    appId: '1:801900444436:web:b7694e6a191fd457202001',
    messagingSenderId: '801900444436',
    projectId: 'suggestions-by-mode',
    authDomain: 'suggestions-by-mode.firebaseapp.com',
    storageBucket: 'suggestions-by-mode.appspot.com',
    measurementId: 'G-3L6D585PFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCypDvzWFPunQ0u2SucntYV2q3cAfCPyOs',
    appId: '1:801900444436:android:6af01ae39bf5f1dd202001',
    messagingSenderId: '801900444436',
    projectId: 'suggestions-by-mode',
    storageBucket: 'suggestions-by-mode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbcH4Zlptsn_k55l37KQ_OKJAhJ00AwUY',
    appId: '1:801900444436:ios:245d59a0eb27aecc202001',
    messagingSenderId: '801900444436',
    projectId: 'suggestions-by-mode',
    storageBucket: 'suggestions-by-mode.appspot.com',
    iosClientId: '801900444436-rb0loee6qkr4v0numo8d298m9i6tph1g.apps.googleusercontent.com',
    iosBundleId: 'com.mervenurtopcu.suggestionsByMode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbcH4Zlptsn_k55l37KQ_OKJAhJ00AwUY',
    appId: '1:801900444436:ios:245d59a0eb27aecc202001',
    messagingSenderId: '801900444436',
    projectId: 'suggestions-by-mode',
    storageBucket: 'suggestions-by-mode.appspot.com',
    iosClientId: '801900444436-rb0loee6qkr4v0numo8d298m9i6tph1g.apps.googleusercontent.com',
    iosBundleId: 'com.mervenurtopcu.suggestionsByMode',
  );
}
